name: Java File Lint

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1.4.4
        with:
          java-version: '17'

      - name: Install Checkstyle
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.43/checkstyle-8.43-all.jar
          echo "alias checkstyle='java -jar checkstyle-8.43-all.jar'" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Run linter
        run: |
          checkstyle -c path/to/checkstyle.xml ${{ github.event.client_payload.paths }}
